# Generated by Django 3.1.4 on 2020-12-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0002_auto_20201221_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
