# Generated by Django 3.1.4 on 2020-12-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0007_auto_20201221_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=256)),
                ('choice_image', models.BinaryField(null=True)),
                ('ballots', models.ManyToManyField(to='gpav_app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='gpav_app.PollChoice')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpav_app.poll'),
        ),
    ]
