# Generated by Django 3.1.4 on 2020-12-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0008_auto_20201223_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.CharField(max_length=32768),
        ),
    ]
