# Generated by Django 3.1.4 on 2020-12-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0009_auto_20201223_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('preview_text', models.CharField(max_length=16384, null=True)),
                ('preview_image', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=5)),
                ('media_data', models.BinaryField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=32768, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpav_app.link'),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(null=True, to='gpav_app.Media'),
        ),
    ]
