# Generated by Django 3.1.4 on 2020-12-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0010_auto_20201223_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(to='gpav_app.Media'),
        ),
    ]
