# Generated by Django 3.1.4 on 2020-12-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0011_auto_20201224_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='link',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='link',
            name='preview_image_url',
            field=models.URLField(null=True),
        ),
    ]
