# Generated by Django 3.1.4 on 2020-12-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0012_auto_20201224_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='preview_image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
