# Generated by Django 3.1.4 on 2020-12-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0013_auto_20201224_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
    ]
