# Generated by Django 3.1.4 on 2020-12-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0014_remove_media_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_data',
            field=models.BinaryField(),
        ),
    ]
