# Generated by Django 3.1.4 on 2020-12-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0015_auto_20201224_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
    ]
