# Generated by Django 3.1.4 on 2020-12-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpav_app', '0016_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
